ProjectMaster.Web/Controllers/GlownaController.cs
using ProjectMaster.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectMaster.Web.Controllers
{
    public class GlownaController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            // jeżeli użytkownik jest zalogowany, to przekieruj na widok projektów
            if (User.Identity.IsAuthenticated)
                return RedirectToAction("Index", "Uzytkownik");

            ViewBag.Message = "Strona startowa";
            return View();
        }
    }
}

ProjectMaster.Web/Views/Shared/NoPermission.cshtml
@{
    ViewBag.Title = "Brak uprawnień";
}

<img src="@Url.Content("~/Images/czegoTuSzukasz.jpg")" alt="IMAGES" />

ProjectMaster.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Project Master</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
    
    <style>
        .modal-content {
            width: 600px !important;
            margin: 30px auto !important;
        }
    </style>


         
</head>
<body>

    <div id="modal-container" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-content">
        </div>
    </div>
  
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                </button>
                @Html.ActionLink("Project Master", "Index", "Glowna", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()

        <hr />
        @*<footer>
            <p>&copy; @DateTime.Now.Year - Design by PG & PG Company</p>
        </footer>*@
    </div>
    
    <script src="~/Scripts/jquery-2.1.3.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    

 

    <script type="text/javascript">
    $(function () {
        // Initialize numeric spinner input boxes
        //$(".numeric-spinner").spinedit();
        // Initialize modal dialog
        // attach modal-container bootstrap attributes to links with .modal-link class.
        // when a link is clicked with these attributes, bootstrap will display the href content in a modal dialog.
        $('body').on('click', '.modal-link', function (e) {
            e.preventDefault();
            $(this).attr('data-target', '#modal-container');
            $(this).attr('data-toggle', 'modal');
        });
        // Attach listener to .modal-close-btn's so that when the button is pressed the modal dialog disappears
        $('body').on('click', '.modal-close-btn', function () {
            $('#modal-container').modal('hide');
        });
        //clear modal cache, so that new content can be loaded
        $('#modal-container').on('hidden.bs.modal', function () {
            $(this).removeData('bs.modal');
        });
        $('#CancelModal').on('click', function () {
            return false;
        });
    });
    </script>



</body>
</html>