ProjectMaster.Web/Controllers/BacklogController.cs
using ProjectMaster.Model;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectMaster.Web.Controllers
{
    public class BacklogController : Controller
    {
        public ActionResult ViewDodajEdytuj(int id, int? idProjektu)
        {
            // nowa instancja backlogu
            Backlog backlog = new Backlog();

            // pobranie projektu
            Projekt aktualnyProjekt;

            List<TypBacklogu> typyBacklogu = new List<TypBacklogu>();
            DaneBacklogu backlogPelny = new DaneBacklogu();
           
            // przy dodawaniu
            if (idProjektu != null)
            {
                // pobranie aktualnego projektu
                aktualnyProjekt = Projekt.Daj(idProjektu);
                backlogPelny.ProjektId = aktualnyProjekt.Id;
            }
            // przy edycji
            else
            {
                backlogPelny.Backlog = Backlog.Daj(id);
                idProjektu = backlogPelny.Backlog.ProjektId;
                aktualnyProjekt = Projekt.Daj(idProjektu);
            }

            // pobranie listy sprintów
            List<Sprint> listaSprintow = aktualnyProjekt.DajSprinty();
            listaSprintow.Insert(0, new Sprint() { Nazwa = "      " });
            if(backlogPelny.Backlog != null)
                listaSprintow.Insert(0, Sprint.Daj(backlogPelny.Backlog.SprintId));
            listaSprintow.Remove(null);

            // pobranie listy użytkowników
            List<Uzytkownik> listaUzytkownikow = aktualnyProjekt.DajUzytkownikowProjektu(idProjektu);
            listaUzytkownikow.Insert(0, new Uzytkownik() { Email = "     " });
            if(backlogPelny.Backlog != null)
                listaUzytkownikow.Insert(0, Uzytkownik.DajUzytkownika(backlogPelny.Backlog.PrzypisanyDoId));
            listaUzytkownikow.Remove(null);

            // stany do SelectList
            backlogPelny.Stany = Stan.DajStanyBacklogow();
            if(backlogPelny.Backlog != null)
                backlogPelny.Stany.Insert(0, Stan.DajStan(backlogPelny.Backlog.StanId));
            backlogPelny.Stany.Remove(null);

            // typy do SelectList
            backlogPelny.Typy = TypBacklogu.DajTypyBacklogow();
            if(backlogPelny.Backlog != null)
                backlogPelny.Typy.Insert(0, TypBacklogu.Daj(backlogPelny.Backlog.TypId));
            backlogPelny.Typy.Remove(null);

            // sprinty i użytkownicy do SelectList
            backlogPelny.Sprinty = listaSprintow;
            backlogPelny.Uzytkownicy = listaUzytkownikow;

            // widok częściowy - okienko
            return PartialView("_DodajEdytuj", backlogPelny);
        }

        [HttpPost]
        public ActionResult DodajEdytuj(DaneBacklogu backlogProjektu, string stan, string sprint, string typ, string uzytkownik)
        {
            bool czyEdycja = true;

            backlogProjektu.Backlog.StanId = Int32.Parse(stan);
            backlogProjektu.Backlog.SprintId = Int32.Parse(sprint);
            backlogProjektu.Backlog.TypId = Int32.Parse(typ);
            backlogProjektu.Backlog.PrzypisanyDoId = Int32.Parse(uzytkownik);
            //backlogProjektu.Backlog.ProjektId = backlogProjektu.ProjektId;

            if (ModelState.ContainsKey("Backlog.Id"))
                ModelState["Backlog.Id"].Errors.Clear();


            if(backlogProjektu.Backlog.ProjektId == 0)
            {
                czyEdycja = false;
                backlogProjektu.Backlog.ProjektId = backlogProjektu.ProjektId;

                if (ModelState.ContainsKey("Backlog.ProjektId"))
                    ModelState["Backlog.ProjektId"].Errors.Clear();
            }

            if (ModelState.IsValid)
            {
                using (var db = new ProjectMasterEntities())
                {
                    if (czyEdycja)
                        db.Entry<Backlog>(backlogProjektu.Backlog).State = EntityState.Modified;
                    else
                        db.Backlogs.Add(backlogProjektu.Backlog);

                    db.SaveChanges();
                }
            }

            // jeżeli ktoś wybierze pusty sprint
            if(backlogProjektu.Backlog.SprintId == 0)
            {
                // pobranie projektu
                Projekt projekt = Projekt.Daj(backlogProjektu.Backlog.ProjektId);

                // przykładowy sprint projektu
                Sprint spr = projekt.DajSprinty()[0];

                // przekieruj do wszystkich backlogów projektu
                return RedirectToAction("Index", "Sprint", new { @id = spr.Id, @idProjektu = projekt.Id });
            }

            return RedirectToAction("Index", "Sprint", new { @id = backlogProjektu.Backlog.SprintId });
            
        }
    }
}

ProjectMaster.Web/Controllers/SprintController.cs
using ProjectMaster.Model;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectMaster.Web.Controllers
{
    public class SprintController : Controller
    {
        // GET: Sprint
        /// <summary>
        /// 
        /// </summary>
        /// <param name="id">Id jednego ze sprinów</param>
        /// <returns></returns>
        public ActionResult Index(int id, int? idProjektu)
        {
            // utworzenie instancji obiektu
            SprintViewModel sprintViewModel = new SprintViewModel();

            // pobranie sprintu
            Sprint sprint = Sprint.Daj(id);
            sprintViewModel.AktualnySprint = sprint;

            // pobranie projektu, w którym jest dany sprint
            Projekt projekt = Projekt.Daj(sprint.ProjektId);
            sprintViewModel.Projekt = projekt;

            // pobranie sprintów danego projektu
            List<Sprint> sprinty = projekt.DajSprinty();
            // przypisanie do wysyłanego modelu
            sprintViewModel.Sprinty = sprinty;

            List<BacklogPelny> backlogi = new List<BacklogPelny>();

            if(idProjektu != null)
            {
                sprintViewModel.CzyWszystkie = true;
                backlogi = projekt.DajBacklogiPelne();
            }
            else
            {
                sprintViewModel.CzyWszystkie = false;
                // pobranie backlogów danego sprintu
                backlogi = sprint.DajBacklogiPelne();
            }
            

            
            sprintViewModel.Backlogi = backlogi;

            sprintViewModel.BacklogiTabela = new List<BacklogViewModel>();
            foreach(var b in backlogi)
            {
                sprintViewModel.BacklogiTabela.Add(new BacklogViewModel()
                    {
                        BacklogPelny = b,
                        ZadaniaBackloga = b.DajZadaniaPelne()
                    });
            }

            // przypisanie aktualnego sprintu

            if (!Zabezpieczenia.UzytkownikProjektu(User.Identity.Name, projekt.Id))
                return View("NoPermission");

            if (Zabezpieczenia.CzyAdminProjektu(User.Identity.Name, projekt.Id))
                sprintViewModel.CzyAdminProjektu = true;

            return View(sprintViewModel);
        }

        public ActionResult Dodaj(int id)
        {
            if (!Zabezpieczenia.CzyAdminProjektu(User.Identity.Name, id))
                return View("NoPermission");

            Sprint sprint = new Sprint()
            {
                Nazwa = string.Format("Sprint{0}", (Sprint.DajLiczbeSprintowProjektu(id) + 1).ToString()),
                ProjektId = id,
                DataUtworzenia = DateTime.Now
            };

            sprint.Dodaj();

            return RedirectToAction("Index", "Sprint", new { @id = sprint.Id });
        }

        public ActionResult ViewEdytuj(int id)
        {
            Sprint sprint = Sprint.Daj(id);
            return PartialView("_Edytuj", sprint);
        }

        [HttpPost]
        public ActionResult Edytuj(Sprint sprint)
        {
            if (ModelState.IsValid)
            {
                using (var db = new ProjectMasterEntities())
                {
                    db.Entry<Sprint>(sprint).State = EntityState.Modified;

                    db.SaveChanges();
                }
            }

            return RedirectToAction("Index", "Sprint", new { @id = sprint.Id });
        }

        //public ActionResult Index(int id, int project)
        //{
        //    return View();
        //}

        //public PartialViewResult Menu(int id)
        //{
        //    Projekt projekt = Projekt.DajProjekt(id);
        //    //SprintViewModel sp = (SprintViewModel)sprint;
        //    //sp.Backlogi = sprint.DajBacklogi();

        //    ProjectViewModel viewModel = new ProjectViewModel()
        //    {
        //        Sprinty = projekt.DajSprinty()
        //    };
        //    return PartialView(viewModel);
        //}

        public ActionResult ViewWyswietlTablice(int id)
        {
            Sprint sprint = Sprint.Daj(id);
            List<Backlog> Backlogi = sprint.DajBacklogi();
            List<Zadanie> zadania = new List<Zadanie>();
            foreach(var b in Backlogi)
            {
                zadania.AddRange(b.DajZadania());
            }

            //List<Zadanie> zadaniaTODO = new List<Zadanie>();
            //foreach(var z in zadania)
            //{
            //    if(z.StanId == Stan.DajStanyZadan())
            //}

            return PartialView("_WyswietlTablice",zadania);
        }

        [HttpPost]
        public ActionResult WyswietlTablice()
        {
            return View("Index");
        }
    }
}

ProjectMaster.Web/Controllers/ZadanieController.cs
using ProjectMaster.Model;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectMaster.Web.Controllers
{
    [Authorize]
    public class ZadanieController : Controller
    {
        // GET: Zadanie
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ViewDodajEdytuj(int id, int? idBacklogu)
        {
            Zadanie zadanie = new Zadanie();

            DaneZadania zadaniePelne = new DaneZadania();
            zadaniePelne.Zadanie = new Zadanie();

            // edycja
            if (idBacklogu == null)
            {
                zadaniePelne.Zadanie = Zadanie.Daj(id);
                idBacklogu = zadaniePelne.Zadanie.BacklogId;

            }

            Backlog backlog = Backlog.Daj(idBacklogu);
            zadaniePelne.Zadanie.BacklogId = backlog.Id;
            int projektId = backlog.ProjektId;
            Projekt aktualnyProjekt = Projekt.Daj(projektId);

            List<Uzytkownik> listaUzytkownikow = aktualnyProjekt.DajUzytkownikowProjektu(projektId);
            listaUzytkownikow.Insert(0, new Uzytkownik() { Email = "     " });
            listaUzytkownikow.Insert(0, Uzytkownik.DajUzytkownika(zadaniePelne.Zadanie.PrzypisanyDoId));
            listaUzytkownikow.Remove(null);
            zadaniePelne.Uzytkownicy = listaUzytkownikow;
            
            zadaniePelne.Stany = Stan.DajStanyZadan();
            zadaniePelne.Stany.Insert(0, Stan.DajStan(zadaniePelne.Zadanie.StanId));
            zadaniePelne.Stany.Remove(null);

            zadaniePelne.Czynnosci = Czynnosc.Daj();
            zadaniePelne.Czynnosci.Insert(0, Czynnosc.Daj(zadaniePelne.Zadanie.CzynnoscId));
            zadaniePelne.Czynnosci.Remove(null);

            return PartialView("_DodajEdytuj", zadaniePelne);
        }

        [HttpPost]
        public ActionResult DodajEdytuj(Zadanie zadanie, string stan, string czynnosc, string uzytkownik)
        {
            zadanie.StanId = Int32.Parse(stan);
            zadanie.CzynnoscId = Int32.Parse(czynnosc);
            zadanie.PrzypisanyDoId = Int32.Parse(uzytkownik);
            int backlogId = zadanie.BacklogId;
            Backlog backlog = Backlog.Daj(backlogId);
            int? idAktualnegoSprintu = backlog.SprintId;

            if (ModelState.IsValid)
            {
                using (var db = new ProjectMasterEntities())
                {
                    if (string.IsNullOrEmpty(zadanie.Opis))
                        zadanie.Opis = " ";

                    if (zadanie.Id != 0)
                        db.Entry<Zadanie>(zadanie).State = EntityState.Modified;
                    else
                        db.Zadanies.Add(zadanie);
                    db.SaveChanges();
                }
            }

            if(idAktualnegoSprintu == 0)
            {
                // pobranie projektu
                Projekt projekt = Projekt.Daj(backlog.ProjektId);

                // przykładowy sprint projektu
                Sprint spr = projekt.DajSprinty()[0];

                // przekieruj do wszystkich backlogów projektu
                return RedirectToAction("Index", "Sprint", new { @id = spr.Id, @idProjektu = projekt.Id });
            }

            return RedirectToAction("Index", "Sprint", new { @id = idAktualnegoSprintu });

        }
        
        public ActionResult Lista()
        {
            Uzytkownik uzytkownik = Uzytkownik.DajUzytkownika(User.Identity.Name);
            List<Zadanie> zadania = uzytkownik.DajZadania();

            return View(zadania);
        }
    }
}

ProjectMaster.Web/Views/Sprint/Index.cshtml
@model ProjectMaster.Model.SprintViewModel

@{
    ViewBag.Title = "Sprinty";
}


    <div id="wrapper">
        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li>
                    @Html.ActionLink("Backlogi", "Index", "Sprint", new { @idProjektu = Model.Projekt.Id }, null)
                </li>
                <li>
                    @Html.ActionLink("Tablica zadań [" + @Model.AktualnySprint.Nazwa + "]", "ViewWyswietlTablice", "Sprint", new { @id = Model.AktualnySprint.Id }, new { @class = "modal-link" })
                </li>
                <li class="sidebar-brand">
                    <a href="#">
                        Sprinty w projekcie:
                    </a>
                </li>
                @foreach (var sprint in Model.Sprinty)
                {
                    if (sprint.Poczatek <= DateTime.Now && sprint.Koniec >= DateTime.Now)
                    {
                        <li>
                            @Html.ActionLink(sprint.Nazwa + " [aktualny]", "Index", new { @id = sprint.Id })
                        </li>
                    }
                    else
                    {
                        <li>
                            @Html.ActionLink(sprint.Nazwa, "Index", new { @id = sprint.Id })
                        </li>
                    }
                }
                @if (Model.CzyAdminProjektu)
                {
                    <li>
                        @Html.ActionLink("Dodaj sprint", "Dodaj", "Sprint", new { @id = Model.Projekt.Id }, new { @class = "przyciskDodaj" })
                    </li>
                }

            </ul>
        </div>


        <div>
            
            @if (Model.CzyAdminProjektu && !Model.CzyWszystkie)
            {
                <br />
                <br />
                if (Model.AktualnySprint.Poczatek == null)
                {
                     @Html.ActionLink("Edytuj sprint", "ViewEdytuj", "Sprint", new { @id = Model.AktualnySprint.Id }, new { @class = "btn btn-default modal-link" })
                }
                else 
                {
                    @Html.ActionLink(Model.AktualnySprint.Poczatek.ToString() + " - " + Model.AktualnySprint.Koniec.ToString(), "ViewEdytuj", "Sprint", new { @id = Model.AktualnySprint.Id }, new { @class = "btn btn-default modal-link" })
                }

            }
        </div>


        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        @if (Model.CzyWszystkie && Model.CzyAdminProjektu)
                        {
                            @Html.ActionLink("Dodaj backlog", "ViewDodajEdytuj", "Backlog", new { @id = 0, @idProjektu = Model.Projekt.Id }, new { @class = "przyciskDodaj modal-link" })
                        }

                        <br />
                        @*@Html.ActionLink("Dodaj backlog", "DodajEdytuj", "Backlog", new { @id = 0 }, new { @class = "przyciskDodaj" })*@
                        @if (!Model.CzyWszystkie)
                        {
                            <h2>@Model.Projekt.Nazwa @Model.Sprinty.Where(s => s.Id == Model.AktualnySprint.Id).FirstOrDefault().Nazwa</h2>
                        }
                        else
                        {
                            <h2>@Model.Projekt.Nazwa Wszystkie backlogi</h2>
                        }
                        <table class="table">

                            <tr>
                                <th>
                                        <a data-toggle="collapse" data-target=".row1">
                                            +
                                        </a>
                                </th>
                                <th>
                                    @Html.Label("Tytuł")
                                </th>
                                <th>
                                    @Html.Label("Stan")
                                </th>
                                <th>
                                    @Html.Label("Przypisany do")
                                </th>
                                <th>
                                    @Html.Label("Wysiłek")
                                </th>
                                <th>
                                    @Html.Label("Warość biznesowa")
                                </th>
                                <th>
                                    @Html.Label("Ukończono [%]")
                                </th>
                                @if(Model.CzyWszystkie)
                                {
                                    <th>
                                        @Html.Label("Sprint")
                                    </th>
                                }
                            </tr>



                            @{int i = 0;}
                            @foreach (var backlog in Model.BacklogiTabela)
                            {
                                i++;
                                <tr>
                                    @*@Html.ActionLink("Dodaj backlog", "DodajEdytuj", "Backlog", new { @id = 0 }, new { @class = "przyciskDodaj" })*@

                                    <td>
                                        @Html.DisplayName(i.ToString())
                                    </td>
                                    <td>
                                        <li class="expand expandDwa">
                                            @Html.ActionLink(backlog.BacklogPelny.Nazwa, "ViewDodajEdytuj", "Backlog", new { @id = backlog.BacklogPelny.Id }, new { @class = "modal-link linkiProjektow" }) <br />
                                            <div>
                                                <ul class="user-menu">
                                                    <li>
                                                        @Html.ActionLink("Edytuj", "ViewDodajEdytuj", "Backlog", new { @id = backlog.BacklogPelny.Id }, new { @class = "modal-link" })

                                                    </li>
                                                    <li>
                                                        @Html.ActionLink("Dodaj zadanie", "ViewDodajEdytuj", "Zadanie", new { @id = 0, @idBacklogu = backlog.BacklogPelny.Id }, new { @class = "modal-link" })
                                                    </li>
                                                </ul>
                                            </div>
                                        </li>

                                        @Html.DisplayFor(b => backlog.BacklogPelny.Opis)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(b => backlog.BacklogPelny.StanP.Nazwa)
                                    </td>
                                    <td>
                                        @Html.DisplayName(backlog.BacklogPelny.Uzytkownik.ToString())
                                    </td>
                                    <td>
                                        @Html.DisplayFor(b => (backlog.BacklogPelny.Wysilek))
                                    </td>
                                    <td>
                                        @Html.DisplayFor(b => (backlog.BacklogPelny.WartoscBiznesowa))
                                    </td>
                                    <td>
                                        @Html.DisplayFor(b => (backlog.BacklogPelny.UkonczonoProcent))
                                    </td>
                                    @if (Model.CzyWszystkie)
                                    {
                                        <td>
                                            @Html.DisplayFor(b => ProjectMaster.Model.Sprint.Daj(backlog.BacklogPelny.SprintId).Nazwa)
                                        </td>
                                    }
                                </tr>
                                foreach (var zadanie in backlog.ZadaniaBackloga)
                                {
                                   @*@Html.ActionLink(backlog.BacklogPelny.Nazwa, "ViewDodajEdytuj", "Backlog", new { @id = backlog.BacklogPelny.Id }, new { @class = "modal-link" }) <br />*@  @*new { @class = "linkiProjektow" }*@
                                    <tr class="collapse row1">
                                        <td></td>
                                        <td>@Html.ActionLink(@zadanie.Nazwa, "ViewDodajEdytuj", "Zadanie", new { @id = zadanie.Id }, new { @class = "modal-link linkiPodprojektow" })</td>
                                        <td>@zadanie.StanP.Nazwa</td>
                                        <td>@zadanie.UzytkownikP.Imie[0] @zadanie.UzytkownikP.Nazwisko</td>
                                        <td>@zadanie.Wysilek</td>
                                        <td></td>
                                        <td>@zadanie.UkonczonoProcent</td>
                                    </tr>
                                }
                            }
                        </table>
                    </div>

                </div>
            </div>
        </div>
    </div>

ProjectMaster.Web/Views/Sprint/_Edytuj.cshtml
@model ProjectMaster.Model.Sprint

@{
    ViewBag.Title = "Edycja sprintu";
}

@*<br />
    <br />*@

<div class="modal-body">
    @using (Html.BeginForm("Edytuj", "Sprint", FormMethod.Post))
    {
        <section>
            <fieldset>
                <legend>Edytuj sprint</legend>
                @Html.HiddenFor(s => s.Id)
                @Html.HiddenFor(s => s.Nazwa)
                @Html.HiddenFor(s => s.ProjektId)
                @Html.HiddenFor(s => s.DataUtworzenia)

                <div class="form-group">
                    @Html.LabelFor(s => s.Poczatek, new { @class = "col-md-3 control-label" })
                    <div class="col-md-9">
                        @Html.TextBoxFor(s => s.Poczatek, new { @class = "form-control" })
                        @Html.ValidationMessageFor(s => s.Poczatek, null, new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(s => s.Koniec, new { @class = "col-md-3 control-label" })
                    <div class="col-md-9">
                        @Html.TextBoxFor(s => s.Koniec, new { @class = "form-control" })
                        @Html.ValidationMessageFor(s => s.Koniec, null, new { @class = "text-danger" })
                    </div>
                </div>


                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <br />
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                        <button type="submit" id="approve-btn" class="btn btn-danger">Save</button>
                    </div>
                </div>

            </fieldset>
            <br />
        </section>
    }
</div>

<script type="text/javascript">
        $(function () {
            $('#approve-btn').click(function () {
                $('#modal-container').modal('hide');
            });
        });
</script>

ProjectMaster.Web/Views/Sprint/_WyswietlTablice.cshtml
@model IEnumerable<ProjectMaster.Model.Zadanie>
@using ProjectMaster.Model

@{
    ViewBag.Title = "Tablica zadan";
}


<div class="modal-body">
    @*<div class="alert alert-warning">*@

        <table class="table table-bordered">
            <tr class="success">
                <td></td>
                <td>Do zrobienia</td>
                <td>W trakcie</td>
                <td>Zrobione</td>
            </tr>
            @foreach (var z in Model)
            {
                <tr>
                    
                    <td class="active">@Backlog.Daj(z.BacklogId).Nazwa</td>
                    <td>
                        @if (Stan.DajStan(z.StanId).Klucz == "TODO")
                        {
                            <h4>@z.Nazwa</h4>
                            <h6>@Uzytkownik.DajUzytkownika(z.PrzypisanyDoId).Email</h6>
                        }
                    </td>
                    <td>
                        @if (Stan.DajStan(z.StanId).Klucz.ToString() == "IN")
                        {
                            <h4>@z.Nazwa</h4>
                            <h6>@Uzytkownik.DajUzytkownika(z.PrzypisanyDoId).Email</h6>
                        }
                    </td>
                    <td>
                        @if (Stan.DajStan(z.StanId).Klucz == "DONE")
                        {
                            <h4>@z.Nazwa</h4>
                            <h6>@Uzytkownik.DajUzytkownika(z.PrzypisanyDoId).Email</h6>
                        }
                    </td>
                </tr>
            }

        </table>
    @*</div>*@

        <div class="row">
            &nbsp;
        </div>
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    
</div>