ProjectMaster.Web/Controllers/ProjektController.cs
using ProjectMaster.Model;
using ProjectMaster.Model.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectMaster.Web.Controllers
{
    [Authorize]
    public class ProjektController : Controller
    {
        /*
         * GET: Projekt/1
         */
        
        public ActionResult Index(int id)
        {
            if (!Zabezpieczenia.UzytkownikProjektu(User.Identity.Name, id))
                return View("NoPermission");

            DaneProjektu dane = Projekt.DajDaneProjektu(id);
            dane.CzyAdminProjektu = false;

            if (Zabezpieczenia.CzyAdminProjektu(User.Identity.Name, id))
                dane.CzyAdminProjektu = true;

            return View(dane);
        }

        [HttpPost]
        public ActionResult Index(int id, string mail, string rolaKlucz)
        {
            DaneProjektu dane = Projekt.DajDaneProjektu(id);
            dane.CzyAdminProjektu = false;

            if (Zabezpieczenia.CzyAdminProjektu(User.Identity.Name, id))
                dane.CzyAdminProjektu = true;

            if(ModelState.IsValid)
            {
                // przypisz role i projekt - bez walidacji (zawsze będą przesłane dobre dane)
                Rola rola = Rola.DajRole(rolaKlucz);
                Projekt projekt = Projekt.Daj(id);

                // waliduj pusty email
                if (string.IsNullOrEmpty(mail))
                {
                    ModelState.AddModelError("", "Brak adresu mail");
                    return View(dane);
                }

                // jak użytkownik nie jest pusty to go przypisz
                Uzytkownik uzytkownik = Uzytkownik.DajUzytkownika(mail);

                // waliduj istnienie użytkownika w bazie danych
                if (uzytkownik == null)
                {
                    ModelState.AddModelError("", "W bazie nie istnieje użytkownik o danym adresie email");
                    return View(dane);
                }

                

                RolaUzytkownikaProjektu rolaUzytkownikaProjektu = new RolaUzytkownikaProjektu() { ProjektId = projekt.Id, UzytkownikId = uzytkownik.Id, RolaId = rola.Id };

                Uzytkownik scrumMaster = new Uzytkownik();
                if(rolaUzytkownikaProjektu.RolaId == 2 && rolaUzytkownikaProjektu.CzyIstniejeScrumMasterProjektu(ref scrumMaster))
                {
                    ModelState.AddModelError("", string.Format("Istnieje scrum master w tym projekcie- usuń użytkownika {0} {1}, aby dodać nowego ScrumMastera", scrumMaster.Imie[0], scrumMaster.Nazwisko));
                    return View(Projekt.DajDaneProjektu(id));
                }
                
                rolaUzytkownikaProjektu.Dodaj();
                    

            }

            dane = Projekt.DajDaneProjektu(id);
            dane.CzyAdminProjektu = false;

            if (Zabezpieczenia.CzyAdminProjektu(User.Identity.Name, id))
                dane.CzyAdminProjektu = true;

            return View(dane);
           // return View();
        }

        [HttpGet]
        public ActionResult Dodaj()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Dodaj(Projekt projekt)
        {
            if(ModelState.IsValid)
            {
                projekt.Utworzyl = User.Identity.Name;
                projekt.Dodaj();

                return RedirectToAction("Index", "Uzytkownik");
            }
            return View(projekt);
        }

        public ActionResult Usun(int id)
        {
            if (!Zabezpieczenia.CzyAdminProjektu(User.Identity.Name, id))
                return View("NoPermission");

            Projekt p = Projekt.Daj(id);
            p.UsunProjekt();

            return RedirectToAction("Index", "Uzytkownik");
        }
            
        public ActionResult UsunUzytkownika(int idProjektu, int idUzytkownika)
        {
            if (!Zabezpieczenia.CzyAdminProjektu(User.Identity.Name, idProjektu))
                return View("NoPermission");

            Projekt p = Projekt.Daj(idProjektu);
            Uzytkownik u = Uzytkownik.DajUzytkownika(idUzytkownika);

            p.UsunUzytkownikaZProjektu(u);

            return RedirectToAction("Index", "Uzytkownik");
        }
      
    }
}

ProjectMaster.Web/Views/Projekt/Dodaj.cshtml
@model ProjectMaster.Model.Projekt
@{
    ViewBag.Title = "Dodawanie projektu";
}

<script>
    $(document).read(function () {

        $("#btnId").click(function () {
            window.alert("sometext");
            var url = '@Url.Action("Index", "Uzytkownik")';
            window.location.href = url;
        });
    });
</script>

<br />
<br />

@using (Html.BeginForm())
{
    <section>
        <fieldset>
            <legend>Dodaj projekt</legend>
            <div class="form-group">
                @Html.LabelFor(p => p.Nazwa, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(p => p.Nazwa, new { @class = "form-control" })
                    @Html.ValidationMessageFor(p => p.Nazwa, null, new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(p => p.Opis, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextAreaFor(p => p.Opis, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">

                    <input type="submit" value="Zapisz" class="btn btn-default" />
                    <input id="btnId" value="Cofnij" class="btn btn-default" type="button" />

                </div>
            </div>
        </fieldset>
        <br />
    </section>
}

ProjectMaster.Web/Views/Projekt/Index.cshtml
@model ProjectMaster.Model.DaneProjektu

@{
    //ViewBag.Title = "Edycja " + @Model.Nazwa;
}

@*Projekt o numerze id: @ViewBag.Id*@


@*<h1>Jesteśmy w projekcie @Model.Nazwa</h1>*@
<br />
<br />

<div class="col-md-5">
    <h3 class="naglowki">Użytkownicy projektu:</h3>
    <table class="table">
    <tr>
        <th>
            @Html.DisplayName("Dane osobowe")
        </th>
        <th>
            @Html.DisplayName("Email")
        </th>
        <td></td>
    </tr>


    @foreach (var uzytkownik in Model.UzytkownicyWProjekcie)
        {
        <tr>
            <td>
                @Html.DisplayName(string.Format("{0} {1}", uzytkownik.Imie[0], uzytkownik.Nazwisko))
                @*@Html.DisplayFor(modelItem => uzytkownik.Imie + " " + modelItem = > uzytkownik.Nazwisko)*@
            </td>
            <td>
                @Html.DisplayFor(modelItem => uzytkownik.Email)
            </td>
            @if (Model.CzyAdminProjektu)
                {
                <td>
                    @Html.ActionLink("Usun", "UsunUzytkownika", "Projekt", new { @idUzytkownika = uzytkownik.Id, @idProjektu = Model.Projekt.Id }, new { @class = "przyciskUsun" })
                </td>
                }

        </tr>
        }

        @if (Model.CzyAdminProjektu)
        {
            using (Html.BeginForm())
                {

                <tr>
                    <td>
                        @Html.TextBox("mail")
                    </td>
                    <td>
                        @Html.DropDownList("rolaKlucz", new List<SelectListItem>() { new SelectListItem() { Selected = true, Text = "Scrum Master", Value = "SMAS" }, new SelectListItem() { Selected = false, Text = "Team Memeber", Value = "TEAM" }, })
                    </td>
                    <td>
                        @*@Html.ActionLink("Dodaj", "DodajUzytkownika", "Projekt", new { @idProjektu = Model.Projekt.Id}, new { @class = "przyciskDodaj" })*@
                        <input type="submit" value="Dodaj" class="bDodaj" />
                    </td>
                </tr> 
                    <tfoot>
                        <tr>
                            <td colspan="3">
                                @Html.Label("Podaj email użytkownika, którego chcesz dodać do projektu i wybierz jego rolę", new { @class = "etykieta" })
                            </td>
                        </tr>
                    </tfoot>
             }
        }
    </table>
    @Html.ValidationSummary()
</div>

<div class="col-md-5">
    @Html.ActionLink("Zarządzaj sprintami", "Index", "Sprint", new { @id = Model.SprintyWProjekcie[0].Id} , null)
</div>